set_property PACKAGE_PIN Y9 [get_ports {A[1]}]
set_property PACKAGE_PIN W9 [get_ports {A[0]}]
set_property DRIVE 12 [get_ports {C[2]}]
set_property DRIVE 12 [get_ports {C[1]}]
set_property DRIVE 12 [get_ports {C[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[0]}]
set_property PACKAGE_PIN AB6 [get_ports {B[1]}]
set_property PACKAGE_PIN AB7 [get_ports {B[0]}]
set_property PACKAGE_PIN D22 [get_ports {C[2]}]
set_property PACKAGE_PIN E22 [get_ports {C[1]}]
set_property PACKAGE_PIN A21 [get_ports {C[0]}]


set_property PACKAGE_PIN K17 [get_ports {D[1]}]
set_property PACKAGE_PIN L13 [get_ports {D[0]}]
set_property PACKAGE_PIN M17 [get_ports {E[1]}]
set_property PACKAGE_PIN M16 [get_ports {E[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {E[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {E[1]}]
